# Label Enconding

In [3]:
from sklearn.preprocessing import LabelEncoder as le
import pandas as pd

In [2]:
d={
    "Climate":["Sunny","Rainy","Windy","Cloudy","Rainy","Stormy"]
}
df=pd.DataFrame(d)
df

  Climate
0   Sunny
1   Rainy
2   Windy
3  Cloudy
4   Rainy
5  Stormy

In [12]:
# Here we create a object and also label is the reference variable.
label=le()
df["encoded_climate"]=label.fit_transform(df["Climate"]) # fit_transform() is used to transform a string into ASCII Value 
df

  Climate  encoded_climate
0   Sunny                3
1   Rainy                1
2   Windy                4
3  Cloudy                0
4   Rainy                1
5  Stormy                2