# Label Enconding

In [8]:
from sklearn.preprocessing import LabelEncoder as le
from sklearn.preprocessing import OneHotEncoder as on
import pandas as pd

In [5]:
d={
    "Climate":["Sunny","Rainy","Windy","Cloudy","Rainy","Stormy"]
}
df=pd.DataFrame(d)
df

  Climate
0   Sunny
1   Rainy
2   Windy
3  Cloudy
4   Rainy
5  Stormy

# LabelEncoder

In [9]:
# Here we create a object and also label is the reference variable.
label=le()
df["encoded_climate"]=label.fit_transform(df["Climate"]) # fit_transform() is used to transform a string into ASCII Value 
df

  Climate  encoded_climate
0   Sunny                3
1   Rainy                1
2   Windy                4
3  Cloudy                0
4   Rainy                1
5  Stormy                2

# OneHot Encoder

In [11]:
onehot=on()
Encoded_value=onehot.fit_transform(df[["Climate"]])

In [34]:
# Sparse Matrix : There is no 1 element present in the matrix.
v1=Encoded_value.toarray()
v1

array([[0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [ ]:
# It is used to find the name of the columns according to the given dataframe.
cl= onehot.get_feature_names_out()
cl

array(['Climate_Cloudy', 'Climate_Rainy', 'Climate_Stormy',
       'Climate_Sunny', 'Climate_Windy'], dtype=object)

In [29]:
df1=pd.DataFrame(v1,columns=cl)
df1

   Climate_Cloudy  Climate_Rainy  Climate_Stormy  Climate_Sunny  Climate_Windy
0             0.0            0.0             0.0            1.0            0.0
1             0.0            1.0             0.0            0.0            0.0
2             0.0            0.0             0.0            0.0            1.0
3             1.0            0.0             0.0            0.0            0.0
4             0.0            1.0             0.0            0.0            0.0
5             0.0            0.0             1.0            0.0            0.0

In [ ]:
df1

   Climate_Cloudy  Climate_Rainy  Climate_Stormy  Climate_Sunny  Climate_Windy
0               0              0               0              1              0
1               0              1               0              0              0
2               0              0               0              0              1
3               1              0               0              0              0
4               0              1               0              0              0
5               0              0               1              0              0

# Ordinal Encoder

In [40]:
from sklearn.preprocessing import OrdinalEncoder

In [38]:
d1={
    "Salary":["High","Low","Medium","Low","High"]
}
df2=pd.DataFrame(d1)
df2

   Salary
0    High
1     Low
2  Medium
3     Low
4    High

In [48]:
code=OrdinalEncoder(categories=[["Low","Medium","High"]])
df2["Encoded_salary"]=code.fit_transform(df2[["Salary"]])
df2

   Salary  Encoded_salary
0    High             2.0
1     Low             0.0
2  Medium             1.0
3     Low             0.0
4    High             2.0